version: "3"
services:
  mysql:
    build: ./mysql/    
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  
    image: mybatis_demo_mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=mybatis   #コンテナ内のMySQLを起動する際のパスワードを設定
    ports:
      - "127.0.0.1:3306:3306"